#!/bin/bash
## `apt-build-archive'
## created by hand <jgmbenoit@rezozer.net>
##
## last major modification 2006/04/13
## last minor modification 2011/04/10
##

## required packages:
##  apt-utils
##  gnupg 

ARCHIVER=/usr/bin/apt-ftparchive
GPG=/usr/bin/gpg

[ -e ${ARCHIVER} ] || exit 2

ARCHIVEDIR="/var/local/cache/apt-build/archives"

REPOSITORYDIR="/var/local/cache/apt-build/repository"

[ -d ${REPOSITORYDIR} ] || exit 1

[ -d ${ARCHIVEDIR} ] || exit 1

CONFIGURATION=${ARCHIVEDIR}/archives.conf

ARCHIVEDISTNAME="local"

[ -f ${CONFIGURATION} ] || exit 1


if [ ! -d "${ARCHIVEDIR}/pool" ]; then
	mkdir --verbose ${ARCHIVEDIR}/pool || exit 2
fi
if [ ! -e "${ARCHIVEDIR}/pool/main" ]; then
	if [ -d "${ARCHIVEDIR}/../repository" ]; then
		true && cd ${ARCHIVEDIR}/pool && ln --verbose -s ../../repository main || exit 2
	else
		true && cd ${ARCHIVEDIR}/pool && ln --verbose -s ${REPOSITORYDIR} main || exit 2
	fi
fi

if [ ! -d ${ARCHIVEDIR}/dists -o ! -h ${ARCHIVEDIR}/dists ] ; then
	true && cd ${ARCHIVEDIR} && ln --verbose -s . dists || exit 2
fi
if [ ! -d "${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}" ]; then
	mkdir --verbose ${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME} || exit 2
fi
if [ ! -d "${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/main" ]; then
	mkdir --verbose ${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/main || exit 2
fi
if [ ! -d "${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/main/binary-amd64" ]; then
	mkdir --verbose ${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/main/binary-amd64 || exit 2
fi

if [ ! -d ${ARCHIVEDIR}/db ]; then
	mkdir --verbose ${ARCHIVEDIR}/db || exit 2
fi
if [ ! -d ${ARCHIVEDIR}/db/dists -o ! -h ${ARCHIVEDIR}/db/dists ] ; then
	true && cd ${ARCHIVEDIR}/db && ln --verbose -s . dists || exit 2
fi
if [ ! -d "${ARCHIVEDIR}/db/dists/${ARCHIVEDISTNAME}" ]; then
	mkdir --verbose ${ARCHIVEDIR}/db/dists/${ARCHIVEDISTNAME} || exit 2
fi


RELEASEDATA="${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/Release"
RELEASEDATAGPG=${RELEASEDATA}.gpg

[ -f ${RELEASEDATAGPG} ] && rm -vf ${RELEASEDATAGPG} 

${ARCHIVER} 'generate' ${CONFIGURATION}

${ARCHIVER} \
		-c ${CONFIGURATION} \
		'release' \
		"${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}" \
	> "${ARCHIVEDIR}/dists/${ARCHIVEDISTNAME}/Release"

${GPG} \
		--homedir /root/.gnupg \
		-sbso ${RELEASEDATAGPG}  \
	${RELEASEDATA}

exit 0
##
## End of file `apt-build-archive'.
